{% set version = "3.14.0.0" %}
{% set sha256 = "612bcc4e857e126c2e1ace98618816209665b20c4136c9e987c67511661715df" %}
{% set build_number = "1" %}  # use for ease of rebasing other branches

package:
  name: uhd
  version: {{ version }}  # [not win]
  version: {{ version }}+1pyapi  # [win and uhd_python_api]
  version: {{ version }}+0nopyapi  # [win and not uhd_python_api]

source:
  url: https://github.com/EttusResearch/uhd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Fix-build-RPATH-remaining-on-installed-libpyuhd.patch
    - 0002-Fix-snprintf-redeclared-as_snprintf.patch

build:
  number: {{ build_number }}
  run_exports:
    - {{ pin_subpackage('uhd', min_pin='x.x.x', max_pin='x.x.x') }}
  script:  # [not uhd_python_api]
    - call %RECIPE_DIR%\bld_nopython.bat  # [not uhd_python_api]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.8
    - jom  # [win]

  host:
    - boost
    - boost-cpp
    - libusb >=1
    - mako >=0.5.0
    - ncurses  # [not win]
    - numpy
    - pkg-config  # [not win]
    - python
    - requests
    - setuptools  # [uhd_python_api]

  run:
    - boost
    - boost-cpp
    # windows requires vs2015+ to build and therefore can't build against py2k
    # so then we don't enable the UHD python library and don't have these deps
    - {{ pin_compatible('numpy') }}  # [uhd_python_api]
    - python  # [uhd_python_api]
    - requests

test:
  commands:
    # verify CLI tools
    {% set uhd_cmds = [
        "uhd_cal_rx_iq_balance",
        "uhd_cal_tx_dc_offset",
        "uhd_cal_tx_iq_balance",
        "uhd_config_info",
        "uhd_find_devices",
        "uhd_image_loader",
        "uhd_images_downloader",  # [linux]
        "uhd_usrp_probe",
        "usrp2_card_burner",  # [linux]
    ] %}
    {% for each_cmd in uhd_cmds %}
    - command -v {{ each_cmd }}  # [unix]
    - where {{ each_cmd }}  # [win]
    {% endfor %}

    # verify libraries
    {% set uhd_lib = "uhd" %}
    - test -f $PREFIX/lib/lib{{ uhd_lib }}${SHLIB_EXT}  # [unix]
    - conda inspect linkages -p $PREFIX uhd  # [not win]
    - conda inspect objects -p $PREFIX uhd  # [osx]

  import:
    - uhd  # [(not win) or py3k]

about:
  home: http://github.com/EttusResearch/uhd
  license: GPL-3.0
  license_file: host/LICENSE
  summary: 'Software driver and API for the Ettus Research USRP SDR platform'
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: http://files.ettus.com/manual/
  dev_url: http://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
